#! /usr/bin/env bash
# Trigger a notification. Useful for long-running commands like CI runs.
# `some_long_running_command && notify "Success!" || notify "Failure!"`

afplay /System/Library/Sounds/Ping.aiff && osascript -e "display notification \"$1\""
